### ISSUE TITLE
Override default toggle not used

### ISSUE THREAD

**Issue by marchsabino** [marchsabino/daylight#3]
The override default toggle in settings is there, but it's not used in `_styles.scss`.  As it is right now, the default input will always be overridden. 

in `_settings.scss` line 4
```SCSS
$set-override-input-defaults: true;
```

in `_styles.scss` line 120
```SCSS
  input {
    -webkit-appearance: none;
    @include border-radius($input-border-radius);
  }
```

This means that no matter what, input elements will have their defaults overridden.  This should be wrapped inside an `@if` statement.
